#  postgres :
  # docker run -p 5432:5432 -d --name postgres -e POSTGRES_PASSWORD=postgrespw -e POSTGRES_USER=postgres -e POSTGRES_DB=cliniquesolis postgres
#  PgAdmin4 :
  # docker run -p 5050:80 -e 'PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org' -e 'PGADMIN_DEFAULT_PASSWORD=admin' -d --name pgadmin4 dpage/pgadmin4
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cliniquesolis
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: 576E5A7234753778214125442A472D4B6150645367556B58703273357638792F
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days