#  postgres :
  # docker run -p 5432:5432 --restart unless-stopped -d --name postgres -e POSTGRES_PASSWORD=postgrespw -e POSTGRES_USER=postgres -e POSTGRES_DB=cliniquesolis postgres
    # when image is installed : docker start postgres
#  PgAdmin4 :
  # docker run -p 5050:80 --restart unless-stopped -e 'PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org' -e 'PGADMIN_DEFAULT_PASSWORD=admin' -d --name pgadmin4 dpage/pgadmin4
    # when image is installed : docker start pgadmin4
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:postgresql://localhost:5432/cliniquesolis
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      # noinspection SpringBootApplicationYaml
      static-locations[0]: "file:src/main/resources/static/"
      # noinspection SpringBootApplicationYaml
      static-locations[1]: "classpath:/static/"
      cache:
        period: 0
application:
  security:
    jwt:
      secret-key: 576E5A7234753778214125442A472D4B6150645367556B58703273357638792F
      expiration: 86400000 # a day # 3600000 # 1 hour
      refresh-token:
        expiration: 604800000 # 7 days