#  postgres :
  # docker run -p 5432:5432 --restart unless-stopped -d --name postgres -e POSTGRES_PASSWORD=postgrespw -e POSTGRES_USER=postgres -e POSTGRES_DB=cliniquesolis postgres
    # when image is installed : docker start postgres
#  PgAdmin4 :
  # docker run -p 5050:80 --restart unless-stopped -e -d --name pgadmin4 dpage/pgadmin4 'PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org' -e 'PGADMIN_DEFAULT_PASSWORD=admin'
    # when image is installed : docker start pgadmin4
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:postgresql://localhost:5432/cliniquesolis
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
    # configure H2 database for tests only
    test:
      datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driver-class-name: org.h2.Driver
      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
            format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect
application:
  security:
    jwt:
      secret-key: 576E5A7234753778214125442A472D4B6150645367556B58703273357638792F
      expiration: 86400000 # a day # 3600000 # 1 hour
      refresh-token:
        expiration: 604800000 # 7 days
